name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start &

      - name: Deploy with pm2
        run: |
          npm install pm2 -g
          pm2 start npm --name Suhail_md_bot
          pm2 save
          pm2 startup
          sudo env PATH=$PATH:/opt/hostedtoolcache/node/20.15.0/x64/bin /opt/hostedtoolcache/node/20.15.0/x64/lib/node_modules/pm2/bin/pm2 startup systemd -u runner --hp /home/runner

      - name: Print PM2 version
        run: pm2 --version

      - name: Print startup command
        run: echo "pm2 startup systemd -u runner --hp /home/runner"

      - name: Run startup command manually
        run: pm2 startup systemd -u runner --hp /home/runner

      - name: Print system logs
        run: sudo journalctl -u pm2

      - name: Setup PM2 startup script
        run: |
          sudo env PATH=$PATH:/opt/hostedtoolcache/node/20.15.0/x64/bin /opt/hostedtoolcache/node/20.15.0/x64/lib/node_modules/pm2/bin/pm2 startup systemd -u runner --hp /home/runner
          echo "Setup PM2 startup script complete"
          
